### ISSUE TITLE
I downloaded this as a alternate to scripthook 

### ISSUE THREAD

**Issue by Believe-ConfessJesus2Bsaved** [fr-Pursuit/AsiSupport#5]
It worked but in vr using lukeross real mod, I only see the game menu not vr world. I removed the scripthook and that’s what happened.

**Comment by fr-Pursuit** [comment]
Unforunately, some ASI scripts don't work well with AsiSupport. It seems like this one is one of them.
Don't worry though, ScriptHookV should be updated soon

**Comment by Believe-ConfessJesus2Bsaved** [comment]
Thanks for your reply. It seemed like a nice possible alternative to
scripthook which never works after updates.

**Comment by fr-Pursuit** [comment]
That's my goal. But unfortunately, AsiSupport doesn't mimic ScriptHookV perfectly. It works on top of RPH, so a few natives that are supported by SHV aren't supported by AsiSupport. Plus, anything related to rendering (other than simply drawing images using the SHV API) isn't implemented in AsiSupport (which mainly explains why your mod doesn't work, if I understood its purpose properly)

**Comment by fr-Pursuit** [comment]
Since this seems to be a mod issue that cannot be fixed considering AsiSupport's current state and ambitions, I'm closing this issue.

**Comment by Believe-ConfessJesus2Bsaved** [comment]
I see another update today caused mods to not work and scripthook update
needed again. Jesus loves you !

**Comment by swamperjon** [comment]
This works great as a scripthook v alternative or as a REPLACEMENT!!! I have NO Problems. Thanks For This Script.

**Comment by Believe-ConfessJesus2Bsaved** [comment]
Glad to hear it! This works fine with mods but what about the lukeross
vrmod  ?
