### ISSUE TITLE
After loading in game and loading the plugin in my game freezes then closes.

### ISSUE THREAD

**Issue by HRKinc** [fr-Pursuit/AsiSupport#7]
Like I stated above after I load in-game and loading the plugin in my game freezes then closes.

[RagePluginHook.log](https://github.com/fr-Pursuit/AsiSupport/files/6166953/RagePluginHook.log)

**Comment by fr-Pursuit** [comment]
It looks like the problem may be coming from a specific ASI mod. Try to remove them, and add them back one by one to see which one's at fault here

**Comment by HRKinc** [comment]
> It looks like the problem may be coming from a specific ASI mod. Try to remove them, and add them back one by one to see which one's at fault here

I removed everything and every one I add one at a time it still crashes I cant use any of them with it.

**Comment by fr-Pursuit** [comment]
Have you emptied the /AsiPlugins directory?
If not, every mod inside this directory will be loaded (basically, ASI Support converts .asi mods to .uasi files to work with them, and keep them in this directory to avoid converting them every time)

**Comment by HRKinc** [comment]
Yup

**Comment by fr-Pursuit** [comment]
Can you put only a generic, innocent mod (like Simple Trainer), and send me the logs if it crashes?

**Comment by HRKinc** [comment]
Yea my game is now randomly crashing give me a sec

**Comment by HRKinc** [comment]
Simple Trainer works

**Comment by HRKinc** [comment]
ELS is the ASI mod that is crashing it is there any way to fix this since it is essential.

**Comment by fr-Pursuit** [comment]
Some people have reported ELS is working fine on the last update. So if you have the latest version of GTA, RPH, ASI Support, and ELS itself, everything should work.
Please note ELS makes your game crash if it is loaded, unloaded, then reloaded without rebooting the game.

If it helps, you can try to load ASI Support (and therefore, ELS) on startup. You may have to increase the plugin termination threshold for this method to work properly

**Comment by HRKinc** [comment]
Thx everything was solved your amazing!!
